port: 4002
author: Mike Mai
title: Designer and Coder
subtitle: UI UX Accessibility
description: Mike Mai is a Chinese designer that specializes in user interface design, user experience design, and web accessibility.
ns: mnml
url: https://mikemai.net
s3: https://s3.amazonaws.com/mikemai
